/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package SeedFinding.util;

import java.util.ArrayList;
import kaptainwutax.mcutils.util.math.NextLongReverser;
import kaptainwutax.mcutils.version.MCVersion;
import kaptainwutax.seedutils.lcg.LCG;
import mjtb49.hashreversals.ChunkRandomReverser;

public class Reverser {
    public static final int TREASURE_RADIUS = 12;

    public static ArrayList<Long> getStructureSeedsFromLootSeeds(ArrayList<Long> seeds) {
        assert (!seeds.isEmpty());
        ArrayList<Long> structureSeeds = new ArrayList<>();
        for (long lootSeed : seeds) {
            ArrayList<Long> decoratorSeeds = new ArrayList<>();
            NextLongReverser.addSeedsToList(lootSeed ^ LCG.JAVA.multiplier, decoratorSeeds);

            for (long internalDecoratorSeed : decoratorSeeds) {
                long decoratorSeed = internalDecoratorSeed ^ 25214903917L;
                long populationSeed = ChunkRandomReverser.reverseDecoratorSeed(decoratorSeed, 1, 3,
                    MCVersion.v1_16_1);
                for (int chunkX = -TREASURE_RADIUS; chunkX < TREASURE_RADIUS; chunkX++) {
                    for (int chunkZ = -TREASURE_RADIUS; chunkZ < TREASURE_RADIUS; chunkZ++) {
                        for (long structureSeed : ChunkRandomReverser.reversePopulationSeed(
                            populationSeed, chunkX << 4, chunkZ << 4, MCVersion.v1_16_1)) {
                            if ((structureSeed & (1L << 48 - 1)) == 0) {
                                continue;
                            }
                            structureSeeds.add(structureSeed);
                        }
                    }
                }
            }
        }
        System.out.println("Finished getting Structure seeds");
        return structureSeeds;
    }
}
